<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9b3ca834-3e12-418f-90d9-ccbf776b0337</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.0.0" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.0.0" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.0.0" />
    <PackageReference Include="Aspire.Hosting.Docker" Version="13.0.0-preview.1.25560.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmsMachineDashboard\SmsMachine.Dashboard.csproj" />
    <ProjectReference Include="..\SmsMachine\SmsMachine.Api.csproj" />
  </ItemGroup>

</Project>
